[package]
name = "egui-bug-example"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = { path = "egui/crates/eframe" }
env_logger = { version = "0.11.8", default-features = false, features = ["auto-color", "humantime"] }
